### ISSUE TITLE
Elevator buttons dataset

### ISSUE THREAD

**Issue by 678098** [zhudelong/elevator_button_recognition#1]
Hello.
Can you possibly publish collected elevator buttons dataset? It's difficult to find any dataset of a kind in open.

**Comment by zhudelong** [comment]
the dataset will be available this weekend. Thanks for your interest!

**Comment by zhudelong** [comment]
> Hello.
> Can you possibly publish collected elevator buttons dataset? It's difficult to find any dataset of a kind in open.

Thanks for your patience, the dataset is available now!

**Comment by linukc** [comment]
@zhudelong Hey, maybe I am just a blinder. I could only find bbox annotations in the dataset. But as mentioned in the [paper](https://arxiv.org/pdf/2103.09030.pdf) instance segmentation annotations (polygons as I expected) have to be as well.
