### ISSUE TITLE
分割数据集

### ISSUE THREAD

**Issue by johnnnya** [zhudelong/elevator_button_recognition#2]
你好，我想咨询下论文里提到的分割数据集在哪里下载

**Comment by zhudelong** [comment]
https://github.com/zhudelong/elevator_button_recognition
主页单击BUTTON_DATASET

**Comment by johnnnya** [comment]
> https://github.com/zhudelong/elevator_button_recognition
> 主页单击BUTTON_DATASET

是iros2018这个文件夹里的吗？文章说总共3718张的电梯面板图像，但是这几个文件夹排布的比较混乱，是需要再用utils里的文件对数据再进行处理吗？

**Comment by zhudelong** [comment]
> > https://github.com/zhudelong/elevator_button_recognition
> > 主页单击BUTTON_DATASET
> 
> 是iros2018这个文件夹里的吗？文章说总共3718张的电梯面板图像，但是这几个文件夹排布的比较混乱，是需要再用utils里的文件对数据再进行处理吗？

里边有个dataset_statistic 的python文件，里边由几个read函数，在里边制定数据集路径即可。电梯面板图像会有稍微调整，最新的benchmark可以参考cascaded OCR-RCNN中给的TIE的文章
